
INPUT_PATH: "../DATA/second_session/Repère/GH010492/"
OUTPUT_PATH: "CREATED_BOP_DATASETS/"
MESH_PATH: "../MESH/repere.json"
MODEL_PATH: "../MESH/"
ANNOTATIONS_PATH: "../ANNOTATIONS/gh010492.mp4-(empty).xml"
INTRINSICS_PATH: '../CALIBRATION/intrinsics.json'
MASK_LINE_THICKNESS: 15
FOR_INFERENCE: True
DEBUG: False