
INPUT_PATH: "../DATA/second_session/Repère/GH010502/"
ANNOTATIONS_PATH: ""
OUTPUT_PATH: "CREATED_BOP_DATASETS/"
MESH_PATH: "../MESH/repere/repere_37.json"
MODEL_PATH: "../MESH/repere/"
N_KEYPOINTS: 4
INTRINSICS_PATH: '../CALIBRATION/intrinsics.json'
MASK_LINE_THICKNESS: 10
FOR_INFERENCE: True
DEBUG: False